language: node_js
node_js:
  - "11.0"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - ./node_modules
  install:
    - npm install -g firebase-tools
    - npm install
  script:
    - npm run ${BUILD}
    - firebase deploy --token $TOKEN --only ${DEPLOY}
jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Client"
      env:
        - BUILD="build:client"
        - DEPLOY="hosting:client"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Admin"
      env:
        - BUILD="build:admin"
        - DEPLOY="hosting:admin"
