version: '2'
services:
    # Sites
    admin:
        build:
            context: .
            args:
                env: admin
        environment:
            - VIRTUAL_HOST=admin.petshop.com
        depends_on:
            - nginx-proxy
    client:
        build:
            context: .
            args:
                env: client
        environment:
            - VIRTUAL_HOST=petshop.com
        depends_on:
            - nginx-proxy
