import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatDividerModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatMenuModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSelectModule,
    MatStepperModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatBadgeModule,
    MatRippleModule,
    MatTabsModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatSlideToggleModule
} from '@angular/material';

@NgModule({
    imports: [
        CommonModule,
        MatInputModule,
        MatCardModule,
        MatButtonModule,
        MatIconModule,
        MatDividerModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatSelectModule,
        MatStepperModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatBadgeModule,
        MatRippleModule,
        MatMenuModule,
        MatTabsModule,
        MatChipsModule,
        MatAutocompleteModule,
        MatSlideToggleModule
    ],
    exports: [
        MatInputModule,
        MatCardModule,
        MatButtonModule,
        MatIconModule,
        MatDividerModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatSelectModule,
        MatStepperModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatBadgeModule,
        MatRippleModule,
        MatMenuModule,
        MatTabsModule,
        MatChipsModule,
        MatAutocompleteModule,
        MatSlideToggleModule
    ],
    declarations: [],
})
export class MaterialModule { }
